title: Teaching With AI
description: Teaching and learning materials
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-include-cache

# Project site settings 
url: "https://teachingwithai.github.io"
baseurl: "/TAI"

# Theme options
# color_scheme: dark
search_enabled: true
